Kdm\ConfigBundle\Doctrine\Orm\Setting:
    type: entity
    id:
        id:
            type: integer
            generator: { strategy: auto }
    fields:
        name:
            type: string
        value:
            type: text
        groupName:
            type: string
        autoload:
            type: boolean
