Kdm\ConfigBundle\Doctrine\Phpcr\Setting:
    id: id
    fields:
        value:
            type: string
            nullable: true
        autoload: boolean
        createdAt:
            type: date
            # gedmo:
            #     timestampable:
            #         on: create
        updatedAt:
            type: date
            # gedmo:
            #     timestampable:
            #         on: update
    parentdocument: group
    nodename: name
    lifecycleCallbacks:
        prePersist: [ onPrePersist ]
        preUpdate: [ onPreUpdate ]
